### ISSUE TITLE
Rethink optical element parameter organization

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#120]
Motivation for the rework:
- a lot of duplicate code because we have to adapt waste box and intersection calculations for each object
- difficult to understand what parameters of the objects are needed where
- get a clear understanding of the process

Graphic for further discussion. It shows a revised flow of object data (parameters)
![TracingProcess drawio](https://user-images.githubusercontent.com/13185253/200281906-a2c0ebde-8db9-411c-9ba7-024c28cd1fd3.svg)

**Comment by Atraxus** [comment]
First two questions for the graphic:
- Is my understanding of how we calculate the precise intersection correct?
- What parameters are used in the different steps? Can there be a clear division?
- Does this division make sense? Would it really improve the implementation?

**Comment by treegardel** [comment]
I don't know how the intersection calculation is implemented at the moment.

In RAY-UI the intersection calculation works a bit more direct: Here the intersection is calculated immediately with the curved surface, then it is checked if the intersection point is inside the boundary - if it is outside, the ray is thrown away.

However, I think that your method of first looking to see if the "waste box" (which should actually be called a hit box) is hit could be more efficient.

However, we would still have to introduce a small improvement: Instead of a flat waste box, we need a 3-dimensional box around the curved surface. If this box is hit, the intersection calculation continues inside the box.
