### ISSUE TITLE
PointSource_seeded test fails under windows

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#136]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/13185253/218102093-f838cf3c-3194-485c-9239-d0c39b610c76.png">

@memoryleak47, do you have an idea what could be going wrong here?

**Comment by OSMaxwell** [comment]
@Alcarin97 I remember you had this issue aswell?..

**Comment by memoryleak47** [comment]
The seeded tests mostly fail due to Random.h giving out different outputs, due to wrong seed / wrong order of random calls.

It could also be due to differences in the random system on windows vs. linux.
We use `std::mt19937` for generating the random numbers.

@Atraxus wanna do a meeting for this in a couple of days?

**Comment by Atraxus** [comment]
Sure, I'll send you a dm
