### ISSUE TITLE
Fix Davids Beamline

### ISSUE THREAD

**Issue by Atraxus** [hz-b/RAY-X#22]
- [x] fix the bugs
- [x] write tests

**Comment by treegardel** [comment]
I think I found an approach to fix the bug: As soon as you set the "Design Angle" to "auto", i.e. overwrite it with the actual "Gracing Incidence Angle", the focus is, as you would expect, at the origin of the "Image Plane". 

Here is the corresponding METRIX "rml" file:
[METRIX_U41_G1_H1_318eV_PS_MLearn_AutoDIA.zip](https://github.com/hz-b/RAY-X/files/8946894/METRIX_U41_G1_H1_318eV_PS_MLearn_AutoDIA.zip)

I have already tried in RAY-X to change the relevant calculations with the "Gracing Incidence Angel" to the "Design Angle". But unfortunately without success.
Who can take over? Preferably also together with me, so that I can see roughly how everything is connected. At the end it was not clear to me which position/orientation of the ellipses are taken over in the shader. Of course, it is still possible that RAY-UI makes a mistake here - the feature with the Design Angle does not exist for a long time.

Here is a simple "rml" file, with which you can also test the issue:
[Ellipsoid_DIA.zip](https://github.com/hz-b/RAY-X/files/8946920/Ellipsoid_DIA.zip)

**Comment by treegardel** [comment]
Together with @memoryleak47, we started to some rework on the ellipsoid implementation. We put the changes on branch: https://github.com/hz-b/RAY-X/tree/ellipsoid-rework
I think, on this branch now the Metrix Beamline is working correctly.

Can somebody confirm this?

**Comment by treegardel** [comment]
- [ ] merge with the development branch
- [ ] write specific test for Ellipse concerning the offset in case curvature design angle is different to the geometrical incidence angle

**Comment by memoryleak47** [comment]
The test Ellipsoid_DIGA fails when activated, see #69.

**Comment by treegardel** [comment]
In my case the test does not fail.
